targets:
  $default:
    builders:
      graphql_codegen:
        options:
          client:
            - graphql
          scalars:
            ISODateTime:
              type: DateTime
            GenericScalar:
              type: Map<String, dynamic>
          scopes:
            - lib/src/gql/**
