name: smartsaver
description: Smart Saver Hiring Task.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.0
  flutter_svg: ^1.0.3
  graphql_flutter: ^5.1.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  json_annotation: ^4.5.0
  graphql: ^5.1.1
  gql: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  graphql_codegen: ^0.8.0
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

assets:
  - assets/images/
